# Generated by Django 6.1.1 on 2026-09-04 15:24

import django.core.validators
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único universal do usuário', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email principal do usuário (usado para login)', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('first_name', models.CharField(blank=True, help_text='Primeiro nome do usuário', max_length=150)),
                ('last_name', models.CharField(blank=True, help_text='Sobrenome do usuário', max_length=150)),
                ('avatar', models.URLField(blank=True, help_text='URL da foto de perfil (vem do Google ou upload)', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designa se o usuário pode fazer login')),
                ('is_staff', models.BooleanField(default=False, help_text='Designa se o usuário tem acesso ao admin Django')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designa se o usuário tem todos os poderes no admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da conta')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'accounts_user',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='accounts_us_created_4734df_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_unique')],
            },
        ),
    ]
