# Generated by Django 6.1.1 on 2026-09-04 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da sessão', primary_key=True, serialize=False)),
                ('session_key', models.CharField(help_text='Chave da sessão Django', max_length=40, unique=True)),
                ('session_type', models.CharField(choices=[('app', 'App'), ('console', 'Console')], default='app', help_text='Tipo de sessão: app ou console', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Endereço IP da sessão', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='User-Agent da sessão', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação da sessão')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Última atividade da sessão', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Data de expiração da sessão (metadado)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Sessão ativa?')),
                ('user', models.ForeignKey(help_text='Usuário da sessão', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão do Usuário',
                'verbose_name_plural': 'Sessões dos Usuários',
                'db_table': 'accounts_user_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'session_type'], name='accounts_us_user_id_e840e8_idx'), models.Index(fields=['is_active', 'created_at'], name='accounts_us_is_acti_fc81d7_idx')],
            },
        ),
    ]
