# Generated by Django 6.1.1 on 2026-09-10 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email principal do usuário (usado para login)', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
