# Generated by Django 6.1.1 on 2026-10-02 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_remove_clienttask_client_task_client__4d55e6_idx_and_more'),
        ('workspaces', '0003_alter_workspaceinvitation_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do arquivo, sem extensão', max_length=255)),
                ('file', models.FileField(help_text='Arquivo físico. O storage é definido por DEFAULT_FILE_STORAGE no projeto.', max_length=500, upload_to='documents/')),
                ('extension', models.CharField(blank=True, help_text='Extensão em minúsculas, sem ponto (ex: "pdf", "m4a")', max_length=20)),
                ('mime_type', models.CharField(blank=True, help_text='MIME type reportado pelo upload', max_length=100)),
                ('size', models.BigIntegerField(default=0, help_text='Tamanho do arquivo em bytes')),
                ('project_id', models.UUIDField(blank=True, db_index=True, help_text='ID de `projects.Project` (UUID solto até o app `projects` existir). NÃO usar como campo genérico de relacionamento.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, help_text='Cliente associado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que subiu o arquivo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Usuário que fez a última alteração', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_documents', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace ao qual o arquivo pertence', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Arquivo criado'), ('renamed', 'Renomeado'), ('replaced', 'Arquivo substituído'), ('client_associated', 'Cliente associado'), ('client_removed', 'Cliente removido'), ('project_associated', 'Projeto associado'), ('project_removed', 'Projeto removido'), ('deleted', 'Excluído')], db_index=True, help_text='Ação executada sobre o documento', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento em que a ação ocorreu')),
                ('previous_value', models.JSONField(blank=True, help_text='Estado anterior (quando aplicável). NULL para ações que não possuem estado anterior.', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='Estado novo (quando aplicável). NULL para ações que não geram novo estado.', null=True)),
                ('document', models.ForeignKey(blank=True, help_text='Documento ao qual este registro se refere. NULL quando o documento já foi excluído.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='documents.document')),
                ('user', models.ForeignKey(blank=True, help_text='Usuário que executou a ação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Arquivo',
                'verbose_name_plural': 'Históricos de Arquivo',
                'db_table': 'document_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', '-created_at'], name='document_workspa_815d1b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'client'], name='document_workspa_dd9a3e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'project_id'], name='document_workspa_a2f725_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'name'], name='document_workspa_dc2bc8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['extension'], name='document_extensi_af57b8_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='document_created_71db36_idx'),
        ),
        migrations.AddIndex(
            model_name='documenthistory',
            index=models.Index(fields=['document', '-timestamp'], name='document_hi_documen_1e2c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='documenthistory',
            index=models.Index(fields=['action', '-timestamp'], name='document_hi_action_285918_idx'),
        ),
        migrations.AddIndex(
            model_name='documenthistory',
            index=models.Index(fields=['user', '-timestamp'], name='document_hi_user_id_31913c_idx'),
        ),
        migrations.AddIndex(
            model_name='documenthistory',
            index=models.Index(fields=['-timestamp'], name='document_hi_timesta_dd45ed_idx'),
        ),
    ]
