# Generated by Django 6.1.1 on 2026-10-02 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_clienttask_client_task_client__4d55e6_idx_and_more'),
        ('documents', '0001_initial'),
        ('workspaces', '0003_alter_workspaceinvitation_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('upload', 'Upload'), ('gdrive', 'Google Drive'), ('url', 'URL')], db_index=True, default='upload', help_text='Como o arquivo entrou no Clivo', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL de origem (Google Drive, URL externa). Apenas registro histórico — não é usada para sincronização.', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['workspace', 'source'], name='document_workspa_4ca5a3_idx'),
        ),
    ]
