# Generated by Django 6.1.1 on 2026-09-12 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('console', '0013_consolegovernance_scope_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do Workspace', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do escritório (ex: "Studio Exemplo")', max_length=150)),
                ('slug', models.SlugField(help_text='Identificador técnico estável (gerado do nome). Nunca exibido diretamente ao usuário.', max_length=150, unique=True)),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ do escritório (opcional)', max_length=18)),
                ('city', models.CharField(blank=True, help_text='Cidade do escritório', max_length=100)),
                ('state', models.CharField(blank=True, help_text='UF do escritório (ex: "BA", "SP")', max_length=2)),
                ('is_active', models.BooleanField(default=True, help_text='Se o Workspace está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'db_table': 'workspace',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='workspace_slug_bb1212_idx'), models.Index(fields=['is_active'], name='workspace_is_acti_d38aa8_idx'), models.Index(fields=['created_at'], name='workspace_created_883e60_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da associação', primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='Quando o usuário entrou no Workspace')),
                ('last_access_at', models.DateTimeField(blank=True, help_text='Último acesso do usuário a este Workspace', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('governance', models.ForeignKey(help_text='Governança do Console atribuída a este usuário neste Workspace. Deve ter scope="workspace".', on_delete=django.db.models.deletion.PROTECT, related_name='workspace_memberships', to='console.consolegovernance')),
                ('user', models.ForeignKey(help_text='Usuário membro do Workspace', on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace ao qual o usuário pertence', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Membro do Workspace',
                'verbose_name_plural': 'Membros do Workspace',
                'db_table': 'workspace_membership',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['workspace', 'user'], name='workspace_m_workspa_d3f494_idx'), models.Index(fields=['user'], name='workspace_m_user_id_d49e9f_idx'), models.Index(fields=['governance'], name='workspace_m_governa_afdf8f_idx'), models.Index(fields=['joined_at'], name='workspace_m_joined__a4c57d_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_user')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da assinatura', primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Se a assinatura está ativa')),
                ('started_at', models.DateTimeField(help_text='Início da vigência desta assinatura')),
                ('ended_at', models.DateTimeField(blank=True, help_text='Fim da vigência (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Plano comercial do Console', on_delete=django.db.models.deletion.PROTECT, related_name='workspace_subscriptions', to='console.plan')),
                ('workspace', models.OneToOneField(help_text='Workspace assinante', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Assinatura de Workspace',
                'verbose_name_plural': 'Assinaturas de Workspace',
                'db_table': 'workspace_subscription',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['workspace', 'is_active'], name='workspace_s_workspa_417355_idx'), models.Index(fields=['plan'], name='workspace_s_plan_id_741654_idx'), models.Index(fields=['started_at'], name='workspace_s_started_2f7c3c_idx')],
            },
        ),
    ]
