# Generated by Django 6.1.1 on 2026-09-12 22:24

import apps.workspaces.models.invitation
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0013_consolegovernance_scope_and_more'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Email do convidado', max_length=254)),
                ('token', models.CharField(db_index=True, default=apps.workspaces.models.invitation._generate_token, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('accepted', 'Aceito'), ('expired', 'Expirado'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Data em que o convite deixa de ser válido')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Quando o convidado se cadastrou e a membership foi criada', null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, help_text='Último envio de email', null=True)),
                ('send_count', models.PositiveIntegerField(default=0, help_text='Quantas vezes o email de convite foi enviado')),
                ('governance', models.ForeignKey(help_text='Governança a ser atribuída quando o convite for aceito', on_delete=django.db.models.deletion.PROTECT, related_name='workspace_invitations', to='console.consolegovernance')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_workspace_invitations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Convite de Workspace',
                'verbose_name_plural': 'Convites de Workspace',
                'db_table': 'workspace_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='workspace_i_workspa_861317_idx'), models.Index(fields=['email', 'status'], name='workspace_i_email_ed5d8c_idx'), models.Index(fields=['token'], name='workspace_i_token_a2019e_idx'), models.Index(fields=['expires_at'], name='workspace_i_expires_e4e23c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('workspace', 'email'), name='unique_pending_invitation_per_workspace_email')],
            },
        ),
    ]
