# Generated by Django 6.1.1 on 2026-09-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspaceinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Data em que o convite deixa de ser válido', null=True),
        ),
    ]
