# Generated by Django 6.1.1 on 2026-09-13 22:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0003_alter_workspaceinvitation_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_code', models.CharField(db_index=True, editable=False, help_text='Código público (ex: CLI-X7K92P). Imutável. Não é senha.', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nome principal (ex: "João & Maria")', max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Email principal de contato', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Contexto publicado/projeção. NÃO é fonte de verdade — é o que o arquiteto decidiu publicar sobre o cliente.')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('archived', 'Arquivado')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_clients', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='Workspace ao qual o cliente pertence', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'client',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('primary', 'Titular'), ('spouse', 'Cônjuge'), ('child', 'Filho(a)'), ('family', 'Familiar'), ('business', 'Profissional'), ('other', 'Outro')], default='other', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Anotações específicas sobre este contato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
            ],
            options={
                'verbose_name': 'Contato do Cliente',
                'verbose_name_plural': 'Contatos do Cliente',
                'db_table': 'client_contact',
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_pinned', models.BooleanField(default=False, help_text='Se a anotação deve aparecer em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_notes', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='clients.client')),
            ],
            options={
                'verbose_name': 'Anotação do Cliente',
                'verbose_name_plural': 'Anotações do Cliente',
                'db_table': 'client_note',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('experience', 'Experiência'), ('issue', 'Problema'), ('suggestion', 'Sugestão')], default='experience', max_length=20)),
                ('rating', models.CharField(blank=True, choices=[('poor', 'Ruim'), ('ok', 'Ok'), ('great', 'Ótimo')], max_length=10)),
                ('message', models.TextField(blank=True, help_text='Comentário livre do cliente')),
                ('page', models.CharField(blank=True, help_text='Página do Portal onde o feedback foi enviado', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_feedbacks', to='clients.client')),
            ],
            options={
                'verbose_name': 'Feedback do Portal',
                'verbose_name_plural': 'Feedbacks do Portal',
                'db_table': 'client_portal_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, help_text='SHA-256 do token de sessão. O token cru NUNCA é armazenado.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='clients.client')),
            ],
            options={
                'verbose_name': 'Sessão de Portal',
                'verbose_name_plural': 'Sessões de Portal',
                'db_table': 'client_portal_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email para o qual o acesso foi enviado', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_invitations', to='clients.client')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_client_portal_invitations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='clients.clientportalsession')),
            ],
            options={
                'verbose_name': 'Convite de Portal',
                'verbose_name_plural': 'Convites de Portal',
                'db_table': 'client_portal_invitation',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPortalAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('accessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_accesses', to='clients.client')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesses', to='clients.clientportalsession')),
            ],
            options={
                'verbose_name': 'Acesso ao Portal',
                'verbose_name_plural': 'Acessos ao Portal',
                'db_table': 'client_portal_access',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('done', 'Concluída'), ('cancelled', 'Cancelada')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('normal', 'Normal'), ('high', 'Alta')], default='normal', max_length=10)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Usuário responsável pela execução', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_client_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarefa do Cliente',
                'verbose_name_plural': 'Tarefas do Cliente',
                'db_table': 'client_task',
                'ordering': ['status', 'due_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('portal.opened', 'Portal acessado'), ('portal.context_confirmed', 'Contexto confirmado pelo cliente'), ('portal.context_edited', 'Contexto corrigido pelo cliente'), ('system.note', 'Nota do sistema')], db_index=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_timeline_events', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='clients.client')),
            ],
            options={
                'verbose_name': 'Evento de Timeline do Cliente',
                'verbose_name_plural': 'Eventos de Timeline do Cliente',
                'db_table': 'client_timeline_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['workspace', 'status'], name='client_workspa_0f535c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['public_code'], name='client_public__a27fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='client_name_57da18_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['created_at'], name='client_created_db23a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('workspace', 'email'), name='unique_client_email_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['client', 'role'], name='client_cont_client__833ae7_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['client', '-created_at'], name='client_note_client__6083ea_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['author'], name='client_note_author__28f749_idx'),
        ),
        migrations.AddIndex(
            model_name='clientnote',
            index=models.Index(fields=['is_pinned'], name='client_note_is_pinn_26d8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalfeedback',
            index=models.Index(fields=['client', '-created_at'], name='client_port_client__9dd7f6_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalfeedback',
            index=models.Index(fields=['kind'], name='client_port_kind_82be52_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalsession',
            index=models.Index(fields=['client', '-created_at'], name='client_port_client__f66dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalsession',
            index=models.Index(fields=['expires_at'], name='client_port_expires_1b9ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalinvitation',
            index=models.Index(fields=['client', '-sent_at'], name='client_port_client__71ac78_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalinvitation',
            index=models.Index(fields=['status'], name='client_port_status_2227a2_idx'),
        ),
        migrations.AddIndex(
            model_name='clientportalaccess',
            index=models.Index(fields=['client', '-accessed_at'], name='client_port_client__f8daa9_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttask',
            index=models.Index(fields=['client', 'status'], name='client_task_client__4d55e6_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttask',
            index=models.Index(fields=['assigned_to', 'status'], name='client_task_assigne_e3e3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttask',
            index=models.Index(fields=['due_at'], name='client_task_due_at_da46c8_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttimelineevent',
            index=models.Index(fields=['client', '-occurred_at'], name='client_time_client__829996_idx'),
        ),
        migrations.AddIndex(
            model_name='clienttimelineevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='client_time_event_t_4b1453_idx'),
        ),
    ]
