# Generated by Django 6.1.1 on 2026-09-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='public_code',
            field=models.CharField(db_index=True, editable=False, help_text='Código público (ex: CLI-X7K92P). Imutável. NÃO é senha.', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('suspended', 'Suspenso')], db_index=True, default='active', help_text='Estado comercial/relacional do cliente.', max_length=20),
        ),
    ]
