# Generated by Django 6.1.1 on 2026-10-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_public_code_alter_client_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clienttask',
            name='client_task_client__4d55e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='clienttask',
            name='client_task_assigne_e3e3c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='clienttask',
            name='client_task_due_at_da46c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='clienttimelineevent',
            name='client_time_client__829996_idx',
        ),
        migrations.RemoveIndex(
            model_name='clienttimelineevent',
            name='client_time_event_t_4b1453_idx',
        ),
        migrations.RemoveField(
            model_name='clienttimelineevent',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='clienttimelineevent',
            name='client',
        ),
        migrations.DeleteModel(
            name='ClientTask',
        ),
        migrations.DeleteModel(
            name='ClientTimelineEvent',
        ),
    ]
