# Generated by Django 6.1.1 on 2026-09-08 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consolegovernance',
            name='governance_type',
            field=models.CharField(choices=[('system', 'System'), ('workspace', 'Workspace'), ('custom', 'Custom')], default='custom', help_text='Tipo da governança', max_length=20),
        ),
        migrations.AddField(
            model_name='consolegovernance',
            name='workspace_id',
            field=models.UUIDField(blank=True, help_text='ID do Workspace associado (apenas para governanças do tipo workspace)', null=True),
        ),
        migrations.AlterField(
            model_name='consolegovernance',
            name='key',
            field=models.CharField(help_text='Chave estável para referência interna (ex: "superadmin", "owner")', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='consolegovernance',
            name='name',
            field=models.CharField(help_text='Nome exibido da governança', max_length=100),
        ),
        migrations.AlterField(
            model_name='consolemembership',
            name='governance',
            field=models.ForeignKey(help_text='Governança do usuário no Console (sempre superadmin)', on_delete=django.db.models.deletion.PROTECT, related_name='members', to='console.consolegovernance'),
        ),
        migrations.AddIndex(
            model_name='consolegovernance',
            index=models.Index(fields=['governance_type'], name='console_gov_governa_9155a8_idx'),
        ),
        migrations.AddIndex(
            model_name='consolegovernance',
            index=models.Index(fields=['workspace_id'], name='console_gov_workspa_aa708b_idx'),
        ),
    ]
