# Generated by Django 6.1.1 on 2026-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_consolegovernance_governance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolecapability',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Se a capability está atualmente declarada por algum app. Capabilities não declaradas viram inativas, mas nunca são deletadas.'),
        ),
        migrations.AlterField(
            model_name='consolecapability',
            name='code',
            field=models.CharField(help_text='Código único da capability no formato "<app>.<recurso>.<ação>" (ex: "clients.client.view")', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='consolecapability',
            name='name',
            field=models.CharField(help_text='Nome exibido da capability', max_length=150),
        ),
        migrations.AlterField(
            model_name='consolecapability',
            name='source_app',
            field=models.CharField(help_text='Label do AppConfig que declarou esta capability. Derivado automaticamente pelo Console — nunca declarado pelo app.', max_length=50),
        ),
        migrations.AddIndex(
            model_name='consolecapability',
            index=models.Index(fields=['is_active'], name='console_cap_is_acti_eff0e5_idx'),
        ),
    ]
