# Generated by Django 6.1.1 on 2026-09-10 19:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_consolecapability_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do plano', primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Chave estável (ex: "free", "basic", "premium")', unique=True)),
                ('name', models.CharField(help_text='Nome exibido (ex: "Free", "Premium")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição comercial do plano')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Preço do plano', max_digits=10)),
                ('currency', models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD')], default='BRL', help_text='Moeda do preço', max_length=3)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('lifetime', 'Lifetime'), ('custom', 'Custom')], default='monthly', help_text='Período de cobrança', max_length=20)),
                ('default_trial_days', models.PositiveIntegerField(default=0, help_text='Sugestão comercial de trial em dias. NÃO é fonte de verdade do trial de um Workspace — a verdade vive em WorkspaceSubscription.trial_ends_at quando existir.')),
                ('is_active', models.BooleanField(default=True, help_text='Se o plano está disponível para novas assinaturas')),
                ('is_public', models.BooleanField(default=True, help_text='Se o plano é visível publicamente para escolha')),
                ('is_system', models.BooleanField(default=False, help_text='Plano nativo do sistema (não pode ser deletado)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou o plano', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'db_table': 'console_plan',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do provider', primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Chave estável (ex: "openai", "cloudinary", "resend")', unique=True)),
                ('name', models.CharField(help_text='Nome exibido (ex: "OpenAI")', max_length=100)),
                ('category', models.SlugField(blank=True, help_text='Categoria informativa (ex: "ai", "storage", "email", "infra"). Não determina comportamento — é apenas para organização visual.')),
                ('description', models.TextField(blank=True, help_text='Descrição do provider')),
                ('is_active', models.BooleanField(default=True, help_text='Se o provider está atualmente em uso pelo Clivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'db_table': 'console_provider',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['key'], name='console_pro_key_30ecc1_idx'), models.Index(fields=['category'], name='console_pro_categor_7fe352_idx'), models.Index(fields=['is_active'], name='console_pro_is_acti_4ed855_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da conexão', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome da conexão (ex: "Clivo Production")', max_length=100)),
                ('environment', models.CharField(choices=[('test', 'Test'), ('production', 'Production')], default='production', help_text='Ambiente da conexão', max_length=20)),
                ('credential_ref', models.CharField(blank=True, help_text='Referência ao secret manager (ex: "vault://clivo/openai/prod"). NUNCA armazenar credenciais em texto puro aqui.', max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Metadados NÃO-secretos (ex: {"cloud_name": "clivo-prod"}). NUNCA armazenar API keys aqui.')),
                ('is_active', models.BooleanField(default=True, help_text='Se a conexão está ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(help_text='Provider associado', on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='console.provider')),
            ],
            options={
                'verbose_name': 'Conexão de Provider',
                'verbose_name_plural': 'Conexões de Provider',
                'db_table': 'console_provider_connection',
                'ordering': ['provider__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do contrato', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do contrato (ex: "Production")', max_length=100)),
                ('external_reference', models.CharField(blank=True, help_text='Referência externa (ex: "org_abc123", "CLD-2026-001")', max_length=255)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time'), ('custom', 'Custom')], default='monthly', help_text='Período de cobrança', max_length=20)),
                ('fixed_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Custo fixo contratado (opcional)', max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD'), ('EUR', 'EUR')], default='BRL', help_text='Moeda do custo', max_length=3)),
                ('started_at', models.DateField(help_text='Data de início do contrato')),
                ('ends_at', models.DateField(blank=True, help_text='Data de término do contrato (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se o contrato está ativo')),
                ('notes', models.TextField(blank=True, help_text='Observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, help_text='Conexão associada (opcional). Um contrato pode ser puramente comercial e não estar ligado a uma conexão específica.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='console.providerconnection')),
                ('provider', models.ForeignKey(help_text='Provider do contrato', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='console.provider')),
            ],
            options={
                'verbose_name': 'Contrato de Provider',
                'verbose_name_plural': 'Contratos de Provider',
                'db_table': 'console_provider_contract',
                'ordering': ['provider__name', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da métrica', primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Chave única da métrica no formato "<domínio>.<recurso>" (ex: "ai.credits", "storage.bytes", "email.sent")', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nome exibido (ex: "AI Credits")', max_length=150)),
                ('unit', models.CharField(help_text='Unidade da métrica (ex: "credit", "byte", "email", "member")', max_length=50)),
                ('kind', models.CharField(choices=[('counter', 'Counter'), ('gauge', 'Gauge'), ('rate', 'Rate')], default='counter', help_text='Tipo de contagem da métrica', max_length=20)),
                ('origin', models.CharField(choices=[('recorded', 'Recorded'), ('derived', 'Derived')], default='recorded', help_text='recorded: o domínio grava UsageRecord. derived: o domínio responde o estado atual via count/sum.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Descrição da métrica')),
                ('is_active', models.BooleanField(default=True, help_text='Se a métrica está disponível para uso em PlanEntitlement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Métrica de Uso',
                'verbose_name_plural': 'Métricas de Uso',
                'db_table': 'console_usage_metric',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['key'], name='console_usa_key_ef46a4_idx'), models.Index(fields=['kind'], name='console_usa_kind_8df5b3_idx'), models.Index(fields=['origin'], name='console_usa_origin_da2fb6_idx'), models.Index(fields=['is_active'], name='console_usa_is_acti_3a0861_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do entitlement', primary_key=True, serialize=False)),
                ('limit_value', models.BigIntegerField(blank=True, help_text='Valor do limite. NULL significa ilimitado.', null=True)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('current', 'Current'), ('lifetime', 'Lifetime')], default='monthly', help_text='Período de reset/aferição do limite', max_length=20)),
                ('behavior', models.CharField(choices=[('hard_limit', 'Hard Limit'), ('soft_limit', 'Soft Limit'), ('overage_allowed', 'Overage Allowed')], default='hard_limit', help_text='Comportamento ao atingir o limite', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Plano associado', on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='console.plan')),
                ('metric', models.ForeignKey(help_text='Métrica associada', on_delete=django.db.models.deletion.PROTECT, related_name='plan_entitlements', to='console.usagemetric')),
            ],
            options={
                'verbose_name': 'Entitlement de Plano',
                'verbose_name_plural': 'Entitlements de Plano',
                'db_table': 'console_plan_entitlement',
                'ordering': ['plan', 'metric__key'],
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['key'], name='console_pla_key_ae62f4_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_active', 'is_public'], name='console_pla_is_acti_9fff3f_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['price'], name='console_pla_price_2cc02e_idx'),
        ),
        migrations.AddIndex(
            model_name='providerconnection',
            index=models.Index(fields=['provider', 'environment'], name='console_pro_provide_e9bc1b_idx'),
        ),
        migrations.AddIndex(
            model_name='providerconnection',
            index=models.Index(fields=['is_active'], name='console_pro_is_acti_5aa1b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerconnection',
            constraint=models.UniqueConstraint(fields=('provider', 'name', 'environment'), name='unique_provider_connection'),
        ),
        migrations.AddIndex(
            model_name='providercontract',
            index=models.Index(fields=['provider', 'is_active'], name='console_pro_provide_1397fe_idx'),
        ),
        migrations.AddIndex(
            model_name='providercontract',
            index=models.Index(fields=['started_at'], name='console_pro_started_f93db7_idx'),
        ),
        migrations.AddIndex(
            model_name='providercontract',
            index=models.Index(fields=['ends_at'], name='console_pro_ends_at_4ccc20_idx'),
        ),
        migrations.AddIndex(
            model_name='planentitlement',
            index=models.Index(fields=['plan', 'metric'], name='console_pla_plan_id_745f70_idx'),
        ),
        migrations.AddIndex(
            model_name='planentitlement',
            index=models.Index(fields=['period'], name='console_pla_period_55ca1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.UniqueConstraint(fields=('plan', 'metric'), name='unique_plan_metric_entitlement'),
        ),
    ]
