# Generated by Django 6.1.1 on 2026-09-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_plan_provider_providerconnection_providercontract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagemetric',
            name='key',
            field=models.CharField(db_index=True, help_text='Chave única da métrica no formato "<domínio>.<recurso>" (ex: "ai.credits", "storage.bytes", "email.sent")', max_length=100, unique=True),
        ),
    ]
