# Generated by Django 6.1.1 on 2026-09-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_alter_usagemetric_key'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consolegovernance',
            name='console_gov_governa_9155a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolegovernance',
            name='console_gov_workspa_aa708b_idx',
        ),
        migrations.AlterField(
            model_name='consolegovernance',
            name='key',
            field=models.CharField(help_text='Chave estável para referência interna (ex: "superadmin")', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='consolemembership',
            name='governance',
            field=models.ForeignKey(help_text='Governança do usuário no Console', on_delete=django.db.models.deletion.PROTECT, related_name='members', to='console.consolegovernance'),
        ),
        migrations.RemoveField(
            model_name='consolegovernance',
            name='governance_type',
        ),
        migrations.RemoveField(
            model_name='consolegovernance',
            name='workspace_id',
        ),
    ]
