# Generated by Django 6.1.1 on 2026-09-10 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_remove_consolegovernance_console_gov_governa_9155a8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consolemembership',
            name='console_mem_governa_3df1c5_idx',
        ),
        migrations.AlterField(
            model_name='consolemembership',
            name='user',
            field=models.OneToOneField(help_text='Usuário associado ao Console', on_delete=django.db.models.deletion.CASCADE, related_name='console_membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='consolemembership',
            name='governance',
        ),
    ]
