# Generated by Django 6.1.1 on 2026-09-11 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_remove_consolemembership_console_mem_governa_3df1c5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consolecapability',
            name='console_cap_code_451869_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolecapability',
            name='console_cap_source__639dc8_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolecapability',
            name='console_cap_created_748166_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolecapability',
            name='console_cap_is_acti_eff0e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolegovernance',
            name='console_gov_key_7426a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolegovernance',
            name='console_gov_is_syst_bc6fc2_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolegovernance',
            name='console_gov_created_e3c499_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolegovernancecapability',
            name='console_gov_governa_f83467_idx',
        ),
        migrations.RemoveIndex(
            model_name='consolegovernancecapability',
            name='console_gov_created_59277e_idx',
        ),
        migrations.RemoveConstraint(
            model_name='consolegovernancecapability',
            name='unique_governance_capability',
        ),
        migrations.RemoveField(
            model_name='consolegovernance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consolegovernancecapability',
            name='capability',
        ),
        migrations.RemoveField(
            model_name='consolegovernancecapability',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='consolegovernancecapability',
            name='governance',
        ),
        migrations.DeleteModel(
            name='ConsoleCapability',
        ),
        migrations.DeleteModel(
            name='ConsoleGovernance',
        ),
        migrations.DeleteModel(
            name='ConsoleGovernanceCapability',
        ),
    ]
