# Generated by Django 6.1.1 on 2026-09-11 23:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_remove_consolecapability_console_cap_code_451869_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da feature', primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Chave estável (ex: "intelligence"). Nunca reutilize uma key após remover a feature.', unique=True)),
                ('name', models.CharField(help_text='Nome exibido (ex: "Intelligence")', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição comercial da feature')),
                ('is_active', models.BooleanField(default=True, help_text='Se a feature está disponível para associação a planos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'console_feature',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['key'], name='console_fea_key_b645b7_idx'), models.Index(fields=['is_active'], name='console_fea_is_acti_917251_idx')],
            },
        ),
        migrations.CreateModel(
            name='FeatureCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da associação', primary_key=True, serialize=False)),
                ('capability_code', models.CharField(help_text='Código estável da capability no formato "<domain>.<resource>.<action>" (ex: "intelligence.analysis.validate").', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou a associação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_capabilities', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(help_text='Feature à qual esta capability pertence', on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='console.feature')),
            ],
            options={
                'verbose_name': 'Capability de Feature',
                'verbose_name_plural': 'Capabilities de Feature',
                'db_table': 'console_feature_capability',
                'ordering': ['feature', 'capability_code'],
                'indexes': [models.Index(fields=['feature'], name='console_fea_feature_e6b7ac_idx'), models.Index(fields=['capability_code'], name='console_fea_capabil_e17679_idx')],
                'constraints': [models.UniqueConstraint(fields=('feature', 'capability_code'), name='unique_feature_capability_code')],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da associação', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou a associação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plan_features', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(help_text='Feature associada ao plano', on_delete=django.db.models.deletion.PROTECT, related_name='plan_features', to='console.feature')),
                ('plan', models.ForeignKey(help_text='Plano', on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='console.plan')),
            ],
            options={
                'verbose_name': 'Feature de Plano',
                'verbose_name_plural': 'Features de Plano',
                'db_table': 'console_plan_feature',
                'ordering': ['plan', 'feature__name'],
                'indexes': [models.Index(fields=['plan'], name='console_pla_plan_id_da4938_idx'), models.Index(fields=['feature'], name='console_pla_feature_e5c6bc_idx')],
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_feature')],
            },
        ),
        migrations.CreateModel(
            name='ProviderLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do log', primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, help_text='ID do Workspace que originou a chamada (temporariamente UUIDField, virará FK).', null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='Quando a chamada ocorreu')),
                ('operation', models.CharField(blank=True, help_text='Operação (ex: "briefing.interpretation")', max_length=255)),
                ('model', models.CharField(blank=True, help_text='Modelo/recurso usado (ex: "gpt-5.6")', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout'), ('rate_limited', 'Rate Limited')], default='success', help_text='Resultado da chamada', max_length=20)),
                ('latency_ms', models.PositiveIntegerField(blank=True, help_text='Latência em milissegundos', null=True)),
                ('input_units', models.BigIntegerField(blank=True, help_text='Unidades de entrada (ex: input tokens)', null=True)),
                ('output_units', models.BigIntegerField(blank=True, help_text='Unidades de saída (ex: output tokens)', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=8, help_text='Custo estimado da chamada', max_digits=18, null=True)),
                ('currency', models.CharField(blank=True, default='USD', help_text='Moeda do custo estimado', max_length=3)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='ID da requisição (opcional)', max_length=255)),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='ID de correlação (opcional)', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Mensagem de erro (se houver)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais (não-secretos)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, help_text='Conexão usada (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='console.providerconnection')),
                ('provider', models.ForeignKey(help_text='Provider chamado', on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='console.provider')),
            ],
            options={
                'verbose_name': 'Log de Provider',
                'verbose_name_plural': 'Logs de Provider',
                'db_table': 'console_provider_log',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['provider', 'occurred_at'], name='console_pro_provide_abf9a8_idx'), models.Index(fields=['status', 'occurred_at'], name='console_pro_status_eb21bb_idx'), models.Index(fields=['workspace_id', 'occurred_at'], name='console_pro_workspa_61936f_idx'), models.Index(fields=['operation'], name='console_pro_operati_fdbd66_idx'), models.Index(fields=['created_at'], name='console_pro_created_09c8df_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProviderPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do pricing', primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, default='', help_text='Identificador específico dentro do provider (ex: "gpt-5.6-input"). Deixe vazio para pricing genérico.', max_length=255)),
                ('pricing_model', models.CharField(choices=[('unit', 'Unit'), ('tiered', 'Tiered'), ('flat', 'Flat'), ('minimum', 'Minimum')], default='unit', help_text='Modelo de precificação', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=8, default=0, help_text='Preço por unidade (ex: 0.000015 USD por token). Use 0 para pricing flat (usa apenas minimum_charge).', max_digits=18)),
                ('currency', models.CharField(choices=[('BRL', 'BRL'), ('USD', 'USD'), ('EUR', 'EUR')], default='USD', help_text='Moeda do preço', max_length=3)),
                ('minimum_charge', models.DecimalField(blank=True, decimal_places=8, help_text='Cobrança mínima (aplicada em pricing_model=minimum).', max_digits=18, null=True)),
                ('included_quantity', models.DecimalField(blank=True, decimal_places=8, help_text='Franquia incluída antes de cobrar (em unidades da métrica).', max_digits=24, null=True)),
                ('starts_at', models.DateTimeField(help_text='Início da vigência deste preço')),
                ('ends_at', models.DateTimeField(blank=True, help_text='Fim da vigência (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Se o pricing está vigente')),
                ('notes', models.TextField(blank=True, help_text='Observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, help_text='Contrato associado (opcional). Se nulo, aplica-se a qualquer contrato ativo do provider.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricings', to='console.providercontract')),
                ('metric', models.ForeignKey(help_text='Métrica à qual este preço se aplica', on_delete=django.db.models.deletion.PROTECT, related_name='provider_pricings', to='console.usagemetric')),
                ('provider', models.ForeignKey(help_text='Provider ao qual este pricing pertence', on_delete=django.db.models.deletion.PROTECT, related_name='pricings', to='console.provider')),
            ],
            options={
                'verbose_name': 'Preço de Provider',
                'verbose_name_plural': 'Preços de Provider',
                'db_table': 'console_provider_pricing',
                'ordering': ['provider__name', 'metric__key', '-starts_at'],
                'indexes': [models.Index(fields=['provider', 'metric', 'is_active'], name='console_pro_provide_9339b4_idx'), models.Index(fields=['contract'], name='console_pro_contrac_8b75cc_idx'), models.Index(fields=['starts_at', 'ends_at'], name='console_pro_starts__3d80c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'metric', 'identifier', 'starts_at'), name='unique_pricing_provider_metric_identifier_starts')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do registro', primary_key=True, serialize=False)),
                ('workspace_id', models.UUIDField(blank=True, db_index=True, help_text='ID do Workspace associado (temporariamente UUIDField, virará FK quando `workspaces` existir).', null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='Quando o consumo ocorreu')),
                ('quantity', models.DecimalField(decimal_places=8, help_text='Quantidade consumida (unidade da métrica). Decimal permite frações (GB, segundos, horas).', max_digits=24)),
                ('unit', models.CharField(help_text='Unidade (ex: "token", "byte", "email")', max_length=50)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='ID da requisição. Quando fornecido, atua como chave de idempotência: dois registros com o mesmo request_id são considerados duplicata.', max_length=255)),
                ('operation', models.CharField(blank=True, help_text='Operação que originou o consumo (ex: "briefing.interpretation")', max_length=255)),
                ('model', models.CharField(blank=True, help_text='Modelo/recurso específico (ex: "gpt-5.6")', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados adicionais (não-secretos)')),
                ('estimated_cost', models.DecimalField(decimal_places=8, default=0, help_text='Custo estimado no momento da criação', max_digits=18)),
                ('currency', models.CharField(default='USD', help_text='Moeda do custo estimado', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='success', help_text='Status do registro', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, help_text='Conexão usada (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='console.providerconnection')),
                ('metric', models.ForeignKey(help_text='Métrica consumida', on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='console.usagemetric')),
                ('provider', models.ForeignKey(help_text='Provider associado', on_delete=django.db.models.deletion.PROTECT, related_name='usage_records', to='console.provider')),
            ],
            options={
                'verbose_name': 'Registro de Uso',
                'verbose_name_plural': 'Registros de Uso',
                'db_table': 'console_usage_record',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['provider', 'occurred_at'], name='console_usa_provide_e3736d_idx'), models.Index(fields=['metric', 'occurred_at'], name='console_usa_metric__f3810e_idx'), models.Index(fields=['workspace_id', 'occurred_at'], name='console_usa_workspa_702be4_idx'), models.Index(fields=['operation'], name='console_usa_operati_6e7003_idx'), models.Index(fields=['created_at'], name='console_usa_created_acfe78_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('request_id__gt', '')), fields=('provider', 'request_id'), name='unique_usage_record_provider_request')],
            },
        ),
    ]
