# Generated by Django 6.1.1 on 2026-09-12 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0009_feature_featurecapability_planfeature_providerlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsoleCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da capability', primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Código único da capability no formato "<app>.<recurso>.<ação>" (ex: "clients.client.view")', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nome exibido da capability', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Descrição da capability')),
                ('source_app', models.CharField(help_text='Label do AppConfig que declarou esta capability. Derivado automaticamente pelo Console — nunca declarado pelo app.', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Se a capability está atualmente declarada por algum app. Capabilities não declaradas viram inativas, mas nunca são deletadas.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
            ],
            options={
                'verbose_name': 'Capacidade do Console',
                'verbose_name_plural': 'Capacidades do Console',
                'db_table': 'console_capability',
                'ordering': ['source_app', 'name'],
                'indexes': [models.Index(fields=['code'], name='console_cap_code_451869_idx'), models.Index(fields=['source_app'], name='console_cap_source__639dc8_idx'), models.Index(fields=['is_active'], name='console_cap_is_acti_eff0e5_idx'), models.Index(fields=['created_at'], name='console_cap_created_748166_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsoleGovernance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da governança', primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='Chave estável para referência interna (ex: "superadmin")', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Nome exibido da governança', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descrição da governança')),
                ('is_system', models.BooleanField(default=False, help_text='Governança nativa do sistema (não pode ser deletada nem editada)')),
                ('is_protected', models.BooleanField(default=False, help_text='Governança protegida (não pode ser deletada, mas pode ser editada)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data da última atualização')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou a governança', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Governança do Console',
                'verbose_name_plural': 'Governanças do Console',
                'db_table': 'console_governance',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsoleGovernanceCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único da associação', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data de criação')),
                ('capability', models.ForeignKey(help_text='Capacidade associada', on_delete=django.db.models.deletion.CASCADE, related_name='governances_relation', to='console.consolecapability')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuário que criou a associação', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_governance_capabilities', to=settings.AUTH_USER_MODEL)),
                ('governance', models.ForeignKey(help_text='Governança associada', on_delete=django.db.models.deletion.CASCADE, related_name='capabilities_relation', to='console.consolegovernance')),
            ],
            options={
                'verbose_name': 'Associação Governança-Capacidade',
                'verbose_name_plural': 'Associações Governança-Capacidade',
                'db_table': 'console_governance_capability',
                'ordering': ['governance', 'capability'],
            },
        ),
        migrations.AddIndex(
            model_name='consolegovernance',
            index=models.Index(fields=['key'], name='console_gov_key_7426a6_idx'),
        ),
        migrations.AddIndex(
            model_name='consolegovernance',
            index=models.Index(fields=['is_system', 'is_protected'], name='console_gov_is_syst_bc6fc2_idx'),
        ),
        migrations.AddIndex(
            model_name='consolegovernance',
            index=models.Index(fields=['created_at'], name='console_gov_created_e3c499_idx'),
        ),
        migrations.AddIndex(
            model_name='consolegovernancecapability',
            index=models.Index(fields=['governance', 'capability'], name='console_gov_governa_f83467_idx'),
        ),
        migrations.AddIndex(
            model_name='consolegovernancecapability',
            index=models.Index(fields=['created_at'], name='console_gov_created_59277e_idx'),
        ),
        migrations.AddConstraint(
            model_name='consolegovernancecapability',
            constraint=models.UniqueConstraint(fields=('governance', 'capability'), name='unique_governance_capability'),
        ),
    ]
