# Generated by Django 6.1.1 on 2026-09-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0010_consolecapability_consolegovernance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolegovernance',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Governança protegida. Não pode ser excluída. Pode ser editada.'),
        ),
        migrations.AlterField(
            model_name='consolegovernance',
            name='is_system',
            field=models.BooleanField(default=False, help_text='Governança nativa do sistema. Não pode ser excluída. Pode ser editada.'),
        ),
        migrations.AlterField(
            model_name='consolegovernance',
            name='key',
            field=models.CharField(help_text='Chave estável para referência interna (ex: "proprietario")', max_length=50, unique=True),
        ),
    ]
