# Generated by Django 6.1.1 on 2026-09-12 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0011_alter_consolegovernance_is_protected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeatureLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único do limite', primary_key=True, serialize=False)),
                ('limit_value', models.BigIntegerField(blank=True, help_text='Valor do limite. NULL significa ilimitado.', null=True)),
                ('period', models.CharField(choices=[('monthly', 'Mensal'), ('current', 'Atual'), ('lifetime', 'Vitalício')], default='monthly', help_text='Período de reset/aferição', max_length=20)),
                ('behavior', models.CharField(choices=[('hard_limit', 'Bloquear ao atingir'), ('soft_limit', 'Avisar ao atingir'), ('overage_allowed', 'Permitir excedente')], default='hard_limit', help_text='Comportamento ao atingir o limite', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Limite de Feature',
                'verbose_name_plural': 'Limites de Feature',
                'db_table': 'console_plan_feature_limit',
                'ordering': ['plan_feature', 'metric__key'],
            },
        ),
        migrations.RemoveIndex(
            model_name='featurecapability',
            name='console_fea_feature_e6b7ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='featurecapability',
            name='console_fea_capabil_e17679_idx',
        ),
        migrations.RemoveConstraint(
            model_name='featurecapability',
            name='unique_feature_capability_code',
        ),
        migrations.RemoveIndex(
            model_name='planentitlement',
            name='console_pla_plan_id_745f70_idx',
        ),
        migrations.RemoveIndex(
            model_name='planentitlement',
            name='console_pla_period_55ca1b_idx',
        ),
        migrations.RemoveConstraint(
            model_name='planentitlement',
            name='unique_plan_metric_entitlement',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='is_system',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Plano inicial. Novos Workspaces começam automaticamente neste plano. Apenas um plano pode ser inicial.'),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se a feature pode ser associada a planos'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='key',
            field=models.SlugField(help_text='Chave técnica estável (gerada do nome). Não é exibida ao operador.', unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='default_trial_days',
            field=models.PositiveIntegerField(default=0, help_text='Sugestão comercial de trial em dias'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='key',
            field=models.SlugField(help_text='Chave estável (gerada automaticamente a partir do nome)', unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(help_text='Nome exibido (ex: "Starter", "Pro")', max_length=100),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usagemetric',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Se a métrica está disponível para uso em PlanFeatureLimit e ProviderPricing'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['is_default'], name='console_pla_is_defa_268806_idx'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_plan'),
        ),
        migrations.AddField(
            model_name='planfeaturelimit',
            name='metric',
            field=models.ForeignKey(help_text='Métrica limitada', on_delete=django.db.models.deletion.PROTECT, related_name='plan_feature_limits', to='console.usagemetric'),
        ),
        migrations.AddField(
            model_name='planfeaturelimit',
            name='plan_feature',
            field=models.ForeignKey(help_text='Feature do plano à qual este limite pertence', on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='console.planfeature'),
        ),
        migrations.RemoveField(
            model_name='featurecapability',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='featurecapability',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='planentitlement',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='planentitlement',
            name='plan',
        ),
        migrations.AddIndex(
            model_name='planfeaturelimit',
            index=models.Index(fields=['plan_feature'], name='console_pla_plan_fe_58b9df_idx'),
        ),
        migrations.AddIndex(
            model_name='planfeaturelimit',
            index=models.Index(fields=['metric'], name='console_pla_metric__0f4aea_idx'),
        ),
        migrations.AddConstraint(
            model_name='planfeaturelimit',
            constraint=models.UniqueConstraint(fields=('plan_feature', 'metric'), name='unique_plan_feature_metric_limit'),
        ),
        migrations.DeleteModel(
            name='FeatureCapability',
        ),
        migrations.DeleteModel(
            name='PlanEntitlement',
        ),
    ]
