# Generated by Django 6.1.1 on 2026-09-12 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0012_planfeaturelimit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consolegovernance',
            name='scope',
            field=models.CharField(choices=[('console', 'Console'), ('workspace', 'Workspace')], db_index=True, default='console', help_text='Onde esta governança pode ser atribuída. "console" → ConsoleMembership. "workspace" → WorkspaceMembership.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='consolegovernance',
            index=models.Index(fields=['scope'], name='console_gov_scope_c201e5_idx'),
        ),
    ]
